[workspace]
members = [
    "bin/sevlamq-cli",
    "bin/sevlamqd",
    "crates/broker",
    "crates/client",
    "crates/common",
    "crates/protocol",
    "crates/storage",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/darlysson/sevlamq"
rust-version = "1.98"

[workspace.dependencies]
bytes = "1.10"
clap = { version = "4.6", features = ["derive"] }
crc32fast = "1.5"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
tokio = { version = "1.47", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "sync", "time"] }
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tempfile = "3.23"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
dbg_macro = "deny"
expect_used = "warn"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
todo = "deny"
unimplemented = "deny"
unwrap_used = "warn"
