[package]
name = "sevlamq-broker"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
crc32fast.workspace = true
sevlamq-common = { path = "../common" }
sevlamq-client = { path = "../client" }
sevlamq-protocol = { path = "../protocol" }
sevlamq-storage = { path = "../storage" }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
